version: '3.4'

services:
  orders.backend.batch:
    image: ${DOCKER_REGISTRY-}ordersbackendbatch
    build:
      context: .
      dockerfile: Orders.Backend/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=PRODUCTION
    ports:
      - "8080:8080"

  orders.frontend.batch:
    image: ${DOCKER_REGISTRY-}ordersfrontendbatch
    build:
      context: .
      dockerfile: Orders.Frontend/Dockerfile
    depends_on:
      - "orders.backend.batch"