version: '3.4'

services:
  orders.rabbitmq.nsb:
    image: "rabbitmq:3-management-alpine"
    hostname: "orders.rabbitmq.nsb"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq.nsb"
      RABBITMQ_DEFAULT_PASS: "rabbitmq.nsb"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq-logging.conf:/etc/rabbitmq/advanced.config
    logging:
        driver: none       

  orders.backend.db.nsb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    logging:
        driver: none  

  orders.backend.nsb:
    image: ${DOCKER_REGISTRY-}ordersbackendnsb
    build:
      context: .
      dockerfile: Orders.Backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "orders.rabbitmq.nsb"
      - "orders.backend.db.nsb"

  orders.frontend.nsb:
    image: ${DOCKER_REGISTRY-}ordersfrontendnsb
    build:
      context: .
      dockerfile: Orders.Frontend/Dockerfile
    depends_on:
      - "orders.rabbitmq.nsb"
      - "orders.backend.nsb"