version: '3.4'

services:
  rabbitmq.nsb:
    image: "rabbitmq:3-management-alpine"
    hostname: "rabbitmq.nsb"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq.nsb"
      RABBITMQ_DEFAULT_PASS: "rabbitmq.nsb"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq-logging.conf:/etc/rabbitmq/advanced.config

  orders.backend.nsb:
    image: ${DOCKER_REGISTRY-}ordersbackendnsb
    build:
      context: .
      dockerfile: Orders.Backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "rabbitmq.nsb"

  orders.frontend.nsb:
    image: ${DOCKER_REGISTRY-}ordersfrontendnsb
    build:
      context: .
      dockerfile: Orders.Frontend/Dockerfile
    depends_on:
      - "rabbitmq.nsb"